# Generated by Django 4.2.1 on 2024-05-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPurchase',
        ),
    ]
