# Generated by Django 4.2.1 on 2024-04-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Event Manager', 'Event Manager')], default='User', max_length=30),
        ),
    ]
