# Generated by Django 4.2.1 on 2024-05-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
    ]
