# Generated by Django 4.2.1 on 2024-05-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_event_available_tickets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
    ]
