# Generated by Django 4.2.1 on 2024-05-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0003_rename_title_event_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type', to='programs.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('ticket_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_code', models.CharField(max_length=255, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
