# Generated by Django 4.2.1 on 2024-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
