# Generated by Django 4.2.1 on 2024-05-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpurchase_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPurchase',
        ),
    ]
