# Generated by Django 4.2.1 on 2024-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_delete_ticketpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
