# Generated by Django 4.2.1 on 2024-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketpurchase_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
